# Generated by Django 5.2.8 on 2025-11-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='budget_preference',
            field=models.CharField(choices=[('FREE', 'Free Only'), ('PAID', 'Can Pay')], default='FREE', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='current_level',
            field=models.CharField(default='Beginner', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='target_career',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
