# Generated by Django 5.2.8 on 2025-11-20 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_budget_preference_user_current_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='node',
        ),
        migrations.RemoveField(
            model_name='roadmapnode',
            name='roadmap',
        ),
        migrations.RemoveField(
            model_name='roadmapnode',
            name='prerequisites',
        ),
        migrations.RemoveField(
            model_name='roadmapnode',
            name='skill',
        ),
        migrations.AlterUniqueTogether(
            name='userskillprogress',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userskillprogress',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='userskillprogress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='description',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='icon_url',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='github_link',
        ),
        migrations.RemoveField(
            model_name='user',
            name='linkedin_link',
        ),
        migrations.RemoveField(
            model_name='user',
            name='uni_skills_tags',
        ),
        migrations.AlterField(
            model_name='user',
            name='target_career',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='UserRoadmapItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('step_order', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('active', 'Active (Learning)'), ('completed', 'Completed')], default='locked', max_length=20)),
                ('market_value', models.CharField(default='Med', max_length=20)),
                ('resources', models.JSONField(blank=True, default=dict)),
                ('project_prompt', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ProjectReview',
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
        migrations.DeleteModel(
            name='Roadmap',
        ),
        migrations.DeleteModel(
            name='RoadmapNode',
        ),
        migrations.DeleteModel(
            name='UserSkillProgress',
        ),
    ]
