# Generated by Django 5.2.8 on 2025-11-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_resource_node_remove_roadmapnode_roadmap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userroadmapitem',
            name='project_submission_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userroadmapitem',
            name='submitted_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
