# Generated by Django 5.2.8 on 2025-11-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userroadmapitem_project_submission_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userroadmapitem',
            name='custom_cv_text',
            field=models.TextField(blank=True, help_text='User edited achievement text', null=True),
        ),
    ]
