# Generated by Django 5.2.8 on 2025-11-22 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_github_link_user_linkedin_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userroadmapitem',
            name='verification_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ProjectReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.userroadmapitem')),
            ],
            options={
                'unique_together': {('submission', 'reviewer')},
            },
        ),
    ]
