# Generated by Django 5.2.8 on 2025-11-24 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_user_groups_alter_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.JSONField(help_text='List of question objects with answers')),
                ('user_answers', models.JSONField(blank=True, default=list, help_text="User's submitted answers")),
                ('score', models.IntegerField(default=0, help_text='Score out of 100')),
                ('passed', models.BooleanField(default=False, help_text='True if score >= 70%')),
                ('attempts', models.IntegerField(default=0, help_text='Number of times user took the quiz')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('roadmap_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='core.userroadmapitem')),
            ],
        ),
    ]
