# Generated by Django 5.2.8 on 2025-11-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_user_email_notifications_user_is_public_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_notifications',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_public',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
