# Generated by Django 5.2.8 on 2026-01-17 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_communitypost_communityreply_posttag_postvote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userroadmapitem',
            name='github_score',
            field=models.IntegerField(default=0, help_text='Automated GitHub project score (0-100)'),
        ),
        migrations.AddField(
            model_name='userroadmapitem',
            name='score_breakdown',
            field=models.JSONField(blank=True, default=dict, help_text='Detailed scoring breakdown'),
        ),
        migrations.AddField(
            model_name='userroadmapitem',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('passed', 'Passed'), ('failed', 'Failed')], default='pending', help_text='Project verification status', max_length=20),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(help_text='Unique certificate ID (e.g., WN-REACT-2026-a3f2)', max_length=50, unique=True)),
                ('github_score', models.IntegerField(help_text='Score at time of certificate issuance')),
                ('peer_verifications', models.IntegerField(default=0, help_text='Peer verification count at issuance')),
                ('score_breakdown', models.JSONField(default=dict, help_text='Detailed breakdown at issuance')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('github_repo_url', models.URLField(blank=True)),
                ('roadmap_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='core.userroadmapitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['certificate_id'], name='core_certif_certifi_30808a_idx'), models.Index(fields=['user', '-issued_at'], name='core_certif_user_id_f684fe_idx')],
            },
        ),
    ]
