# Generated by Django 5.2.8 on 2026-01-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_premium_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activity_visibility',
            field=models.JSONField(blank=True, default=dict, help_text='Per-section visibility toggles for profile activity.'),
        ),
        migrations.AddField(
            model_name='user',
            name='allow_indexing',
            field=models.BooleanField(default=True, help_text='Allow search engines to index this profile when public.'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_visibility',
            field=models.CharField(choices=[('public', 'Public'), ('community', 'Community-only'), ('private', 'Private')], default='public', help_text='Who can view this profile inside the app.', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='website_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
