# Generated by Django 5.2.8 on 2026-01-19 11:27

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_user_activity_visibility_user_allow_indexing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='employer',
        ),
        migrations.AddField(
            model_name='user',
            name='last_active_module_id',
            field=models.ForeignKey(blank=True, help_text='Last module user was working on', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_active_for_user', to='core.userroadmapitem'),
        ),
        migrations.AddField(
            model_name='user',
            name='community_xp',
            field=models.IntegerField(default=0, help_text='Community engagement points (+10 per post, +5 per reply)'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_active_at',
            field=models.DateTimeField(blank=True, help_text='Last time user accessed any module', null=True),
        ),
        migrations.AddField(
            model_name='userroadmapitem',
            name='lesson_cached_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when lesson was last cached (use for TTL expiration)', null=True),
        ),
        migrations.AddField(
            model_name='userroadmapitem',
            name='lesson_data',
            field=models.JSONField(blank=True, default=dict, help_text='Cached lesson data to avoid regenerating on every module view', null=True),
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_type', models.CharField(choices=[('first_module', 'First Module'), ('streak_7', '7-Day Streak'), ('streak_30', '30-Day Streak'), ('modules_5', 'Five Modules'), ('modules_10', 'Ten Modules'), ('verified_project', 'Verified Project'), ('verified_5', 'Five Verified Projects'), ('community_contributor', 'Community Contributor'), ('top_contributor', 'Top Contributor This Week')], max_length=50)),
                ('icon_url', models.URLField(blank=True, help_text='SVG icon or image URL for the badge')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-awarded_at'],
                'unique_together': {('user', 'badge_type')},
            },
        ),
        migrations.CreateModel(
            name='SavedResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('news', 'Tech News'), ('video', 'Video'), ('job', 'Job Posting'), ('article', 'Article'), ('documentation', 'Documentation')], max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField()),
                ('source', models.CharField(help_text="e.g., 'Tech Crunch', 'YouTube', 'WeWorkRemotely'", max_length=100)),
                ('description', models.TextField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of tags for filtering')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('associated_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_resources', to='core.userroadmapitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-saved_at'],
            },
        ),
        migrations.DeleteModel(
            name='CandidateApplication',
        ),
        migrations.DeleteModel(
            name='JobPosting',
        ),
        migrations.AddIndex(
            model_name='savedresource',
            index=models.Index(fields=['user', '-saved_at'], name='core_savedr_user_id_cba630_idx'),
        ),
        migrations.AddIndex(
            model_name='savedresource',
            index=models.Index(fields=['resource_type', '-saved_at'], name='core_savedr_resourc_cf02c8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='savedresource',
            unique_together={('user', 'url')},
        ),
    ]
