# Generated by Django 5.2.8 on 2026-01-19 15:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_jobposting_employer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_seed',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('unspecified', 'Prefer not to say'), ('female', 'Female'), ('male', 'Male'), ('nonbinary', 'Non-binary')], default='unspecified', help_text='Self-reported gender (used for personalization; not required).', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='last_username_change_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
