# Generated by Django 5.2.8 on 2026-02-09 00:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_user_avatar_seed_user_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleRoadmapTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('fullstack', 'Full-Stack Developer'), ('frontend', 'Frontend Developer'), ('backend', 'Backend Developer'), ('data', 'Data Scientist'), ('devops', 'DevOps Engineer'), ('mobile', 'Mobile Developer')], max_length=30, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('modules', models.JSONField(default=list, help_text='Ordered list of module dicts: label, description, market_value, project_prompt, resources, lessons, connections')),
                ('version', models.IntegerField(default=1, help_text='Bump when updating the template')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['role'],
            },
        ),
        migrations.AlterField(
            model_name='badge',
            name='badge_type',
            field=models.CharField(choices=[('first_module', 'First Module'), ('streak_7', '7-Day Streak'), ('streak_30', '30-Day Streak'), ('modules_5', 'Five Modules'), ('modules_10', 'Ten Modules'), ('verified_project', 'Verified Project'), ('verified_5', 'Five Verified Projects'), ('community_contributor', 'Community Contributor'), ('top_contributor', 'Top Contributor This Week'), ('product_thinker', 'Product Thinker'), ('communicator', 'Strong Communicator'), ('soft_skills', 'Soft Skills Champion')], max_length=50),
        ),
        migrations.CreateModel(
            name='JadaConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('general', 'General Chat'), ('lesson', 'Lesson Help'), ('review', 'Code Review'), ('manager', 'Manager Mode'), ('architect', 'Architect Mode')], default='general', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_message_at', models.DateTimeField(auto_now=True)),
                ('context_module', models.ForeignKey(blank=True, help_text='Module context for this conversation', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.userroadmapitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jada_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='JadaMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('jada', 'JADA'), ('system', 'System')], max_length=10)),
                ('content', models.TextField()),
                ('model_used', models.CharField(blank=True, help_text='e.g. llama-3.1, deepseek-r1', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.jadaconversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(default='landing', help_text='landing, referral, social', max_length=50)),
                ('synced_to_loops', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_entry', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(blank=True, max_length=500)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.userroadmapitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_clicks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-clicked_at'],
                'indexes': [models.Index(fields=['url', '-clicked_at'], name='core_resour_url_8838db_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserFollowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('follower', 'following')},
            },
        ),
        migrations.CreateModel(
            name='UserTechDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('skipped_count', models.IntegerField(default=1)),
                ('last_skipped_at', models.DateTimeField(auto_now=True)),
                ('resolved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_debts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-skipped_count'],
                'unique_together': {('user', 'topic')},
            },
        ),
    ]
