# Generated by Django 5.2.8 on 2026-02-18 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_roleroadmaptemplate_alter_badge_badge_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_id', models.CharField(help_text='AI-generated lesson identifier (e.g. "lesson_1")', max_length=100)),
                ('lesson_title', models.CharField(blank=True, max_length=300)),
                ('is_completed', models.BooleanField(default=False)),
                ('quiz_passed', models.BooleanField(default=False)),
                ('quiz_questions', models.JSONField(blank=True, default=list, help_text='5 MCQ questions generated by AI')),
                ('quiz_answers', models.JSONField(blank=True, default=list, help_text="User's submitted answers")),
                ('quiz_score', models.IntegerField(default=0, help_text='Score out of 100')),
                ('quiz_attempts', models.IntegerField(default=0)),
                ('confidence_rating', models.IntegerField(blank=True, help_text='Self-assessed 0-100', null=True)),
                ('xp_awarded', models.IntegerField(default=0)),
                ('time_spent_seconds', models.IntegerField(default=0, help_text='Approximate time spent on lesson')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('roadmap_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to='core.userroadmapitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['roadmap_item', 'lesson_id'],
                'unique_together': {('user', 'roadmap_item', 'lesson_id')},
            },
        ),
    ]
