# Generated by Django 5.2.8 on 2026-02-18 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_lesson_progress'),
    ]

    operations = [
        # search_vector was removed from 0018 before ever being applied;
        # this migration is kept as a no-op to preserve the dependency chain.
    ]
