# Generated by Django 5.2.8 on 2026-02-18 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_lesson_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitypost',
            name='search_vector',
        ),
    ]
