# Generated by Django 5.2.8 on 2026-02-24 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_communitypost_search_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='jadaconversation',
            name='session_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Anonymous session ID for guest conversations', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, default='', help_text='Persisted DiceBear avatar URL. Set once from avatar_seed.'),
        ),
        migrations.AlterField(
            model_name='jadaconversation',
            name='mode',
            field=models.CharField(choices=[('general', 'General Chat'), ('lesson', 'Lesson Help'), ('review', 'Code Review'), ('manager', 'Manager Mode'), ('architect', 'Architect Mode'), ('consultant', 'Career Consultant')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='jadaconversation',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Null for guest (pre-signup) conversations', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jada_conversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
