from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings

# ==========================================
# 1. USER & PROFILE
# ==========================================

class User(AbstractUser):
    """
    Custom user model to store University data and Career Goals.
    """
    university_course_raw = models.CharField(max_length=255, blank=True, help_text="User's input (e.g. 'Bsc Acctng')")
    normalized_course = models.CharField(max_length=255, blank=True, help_text="AI cleaned version (e.g. 'Accounting')")
    
    github_link = models.URLField(blank=True, null=True)
    linkedin_link = models.URLField(blank=True, null=True)
    
    target_career = models.CharField(max_length=255, blank=True, default="")
    budget_preference = models.CharField(
        max_length=10, 
        choices=[('FREE', 'Free Only'), ('PAID', 'Can Pay')],
        default='FREE'
    )
    current_level = models.CharField(max_length=50, default="Beginner")
    reputation_score = models.IntegerField(default=0, help_text="Points gained from reviewing others")
    
    groups = models.ManyToManyField(
        'auth.Group',
        verbose_name='groups',
        blank=True,
        help_text='The groups this user belongs to.',
        related_name="core_user_set",
        related_query_name="core_user",
    )
    user_permissions = models.ManyToManyField(
        'auth.Permission',
        verbose_name='user permissions',
        blank=True,
        help_text='Specific permissions for this user.',
        related_name="core_user_set",
        related_query_name="core_user",
    )

    def __str__(self):
        return self.username

# ==========================================
# 2. THE PERSONALIZED ROADMAP
# ==========================================

class UserRoadmapItem(models.Model):
    """
    Stores a specific node generated by AI for a specific user.
    """
    STATUS_CHOICES = [
        ('locked', 'Locked'),
        ('active', 'Active (Learning)'),
        ('completed', 'Completed'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='roadmap_items')
    label = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    step_order = models.IntegerField(default=0)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='locked')
    market_value = models.CharField(max_length=20, default="Med")
    project_submission_link = models.URLField(blank=True, null=True)
    submitted_at = models.DateTimeField(auto_now=True)
    resources = models.JSONField(default=dict, blank=True)
    project_prompt = models.TextField(blank=True)
    verification_count = models.IntegerField(default=0)
    custom_cv_text = models.TextField(blank=True, null=True, help_text="User edited achievement text")
    
    def __str__(self):
        return f"{self.user.username} -> {self.label} ({self.status})"

# ==========================================
# 3. COMMUNITY MODELS
# ==========================================

class Skill(models.Model):
    name = models.CharField(max_length=100, unique=True)
    def __str__(self): 
        return self.name

class ProjectReview(models.Model):
    """
    Tracks which users verified which projects (for reputation).
    """
    submission = models.ForeignKey(UserRoadmapItem, on_delete=models.CASCADE, related_name='reviews')
    reviewer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('submission', 'reviewer')

    def __str__(self):
        return f"{self.reviewer.username} verified {self.submission.label}"

# ==========================================
# 4. STREAK SYSTEM
# ==========================================

class UserActivity(models.Model):
    """
    Tracks daily contribution counts for the streak graph.
    """
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='activities')
    date = models.DateField()
    count = models.IntegerField(default=0)

    class Meta:
        unique_together = ('user', 'date')

# ==========================================
# 5. QUIZ SYSTEM
# ==========================================

class Quiz(models.Model):
    """
    AI-generated quiz for each roadmap module.
    """
    roadmap_item = models.OneToOneField(UserRoadmapItem, on_delete=models.CASCADE, related_name='quiz')
    questions = models.JSONField(help_text="List of question objects with answers")
    user_answers = models.JSONField(default=list, blank=True, help_text="User's submitted answers")
    score = models.IntegerField(default=0, help_text="Score out of 100")
    passed = models.BooleanField(default=False, help_text="True if score >= 70%")
    attempts = models.IntegerField(default=0, help_text="Number of times user took the quiz")
    completed_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"Quiz for {self.roadmap_item.label} - Score: {self.score}%"