from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings

# ==========================================
# 1. USER & PROFILE
# ==========================================

class User(AbstractUser):
    """
    Custom user model to store University data and Career Goals.
    """
    email = models.EmailField(unique=True)
    university_course_raw = models.CharField(max_length=255, blank=True, help_text="User's input (e.g. 'Bsc Acctng')")
    normalized_course = models.CharField(max_length=255, blank=True, help_text="AI cleaned version (e.g. 'Accounting')")
    
    target_career = models.CharField(max_length=255, blank=True)
    budget_preference = models.CharField(max_length=10, choices=[('FREE', 'Free Only'), ('PAID', 'Can Pay')], default='FREE')
    current_level = models.CharField(max_length=50, default='Beginner')
    reputation_score = models.IntegerField(default=0)

    github_link = models.URLField(blank=True, null=True)
    linkedin_link = models.URLField(blank=True, null=True)

    groups = models.ManyToManyField(
        'auth.Group',
        verbose_name='groups',
        blank=True,
        help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
        related_name="core_user_set",
        related_query_name="core_user",
    )
    user_permissions = models.ManyToManyField(
        'auth.Permission',
        verbose_name='user permissions',
        blank=True,
        help_text='Specific permissions for this user.',
        related_name="core_user_set",
        related_query_name="core_user",
    )

    def __str__(self):
        return self.username

# ==========================================
# 2. THE PERSONALIZED ROADMAP
# ==========================================

class UserRoadmapItem(models.Model):
    """
    Stores a specific node generated by AI for a specific user.
    """
    STATUS_CHOICES = [
        ('locked', 'Locked'),
        ('active', 'Active (Learning)'),
        ('completed', 'Completed'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='roadmap_items')
    label = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    step_order = models.IntegerField(default=0)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='locked')
    market_value = models.CharField(max_length=20, default="Med")
    project_submission_link = models.URLField(blank=True, null=True)
    submitted_at = models.DateTimeField(auto_now=True)
    resources = models.JSONField(default=dict, blank=True)
    project_prompt = models.TextField(blank=True)
    verification_count = models.IntegerField(default=0)
    custom_cv_text = models.TextField(blank=True, null=True, help_text="User edited achievement text")
    
    def __str__(self):
        return f"{self.user.username} -> {self.label} ({self.status})"

# ==========================================
# 3. COMMUNITY MODELS
# ==========================================

class Skill(models.Model):
    name = models.CharField(max_length=100, unique=True)
    def __str__(self): 
        return self.name

class ProjectReview(models.Model):
    """
    Tracks which users verified which projects (for reputation).
    """
    VOTE_CHOICES = [
        ('up', 'Upvote'),
        ('down', 'Downvote'),
    ]
    submission = models.ForeignKey(UserRoadmapItem, on_delete=models.CASCADE, related_name='reviews')
    reviewer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    vote_type = models.CharField(max_length=10, choices=VOTE_CHOICES, default='up')
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('submission', 'reviewer')

    def __str__(self):
        return f"{self.reviewer.username} verified {self.submission.label}"

class ProjectComment(models.Model):
    project = models.ForeignKey(UserRoadmapItem, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    text = models.TextField(max_length=2000)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"Comment by {self.author.username} on {self.project.label}"

# ==========================================
# 4. STREAK SYSTEM
# ==========================================

class UserActivity(models.Model):
    """
    Tracks daily contribution counts for the streak graph.
    """
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='activities')
    date = models.DateField()
    count = models.IntegerField(default=0)

    class Meta:
        unique_together = ('user', 'date')

# ==========================================
# 5. QUIZ SYSTEM
# ==========================================

class Quiz(models.Model):
    """
    AI-generated quiz for each roadmap module.
    """
    roadmap_item = models.OneToOneField(UserRoadmapItem, on_delete=models.CASCADE, related_name='quiz')
    questions = models.JSONField(help_text="List of question objects with answers")
    user_answers = models.JSONField(default=list, blank=True, help_text="User's submitted answers")
    score = models.IntegerField(default=0, help_text="Score out of 100")
    passed = models.BooleanField(default=False, help_text="True if score >= 70%")
    attempts = models.IntegerField(default=0, help_text="Number of times user took the quiz")
    completed_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"Quiz for {self.roadmap_item.label} - Score: {self.score}%"

# ==========================================
# 6. EMPLOYER PROFILES & JOB POSTINGS
# ==========================================

class EmployerProfile(models.Model):
    """
    Profile for employers/recruiters using the platform.
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='employer_profile')
    company_name = models.CharField(max_length=255)
    company_logo_url = models.URLField(blank=True)
    company_website = models.URLField(blank=True)
    industry = models.CharField(max_length=100, blank=True)
    is_verified = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"{self.company_name}"

class JobPosting(models.Model):
    """
    Job postings created by employers.
    """
    LEVEL_CHOICES = [
        ('intern', 'Internship'),
        ('entry', 'Entry-Level'),
        ('junior', 'Junior'),
    ]
    
    employer = models.ForeignKey(EmployerProfile, on_delete=models.CASCADE, related_name='job_postings')
    title = models.CharField(max_length=255)
    description = models.TextField()
    required_skills = models.JSONField(default=list, help_text="List of required skill keywords")
    level = models.CharField(max_length=10, choices=LEVEL_CHOICES, default='entry')
    location = models.CharField(max_length=255, default='Remote')
    salary_range = models.CharField(max_length=100, blank=True)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"{self.title} at {self.employer.company_name}"

class CandidateApplication(models.Model):
    """
    Tracks applications of learners to job postings.
    """
    STATUS_CHOICES = [
        ('applied', 'Applied'),
        ('reviewed', 'Reviewed'),
        ('shortlisted', 'Shortlisted'),
        ('interview', 'Interview'),
        ('offer', 'Offer'),
        ('rejected', 'Rejected'),
    ]
    
    job_posting = models.ForeignKey(JobPosting, on_delete=models.CASCADE, related_name='applications')
    candidate = models.ForeignKey(User, on_delete=models.CASCADE, related_name='job_applications')
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='applied')
    match_score = models.IntegerField(default=0, help_text="Skill match percentage 0-100")
    applied_at = models.DateTimeField(auto_now_add=True)
    target_career = models.CharField(max_length=255, blank=True)
    budget_preference = models.CharField(max_length=10, choices=[('FREE', 'Free Only'), ('PAID', 'Can Pay')], default='FREE')
    current_level = models.CharField(max_length=50, default='Beginner')
    reputation_score = models.IntegerField(default=0)

    github_link = models.URLField(blank=True, null=True)
    linkedin_link = models.URLField(blank=True, null=True)

    groups = models.ManyToManyField(
        'auth.Group',
        verbose_name='groups',
        blank=True,
        help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
        related_name="core_user_set",
        related_query_name="core_user",
    )
    user_permissions = models.ManyToManyField(
        'auth.Permission',
        verbose_name='user permissions',
        blank=True,
        help_text='Specific permissions for this user.',
        related_name="core_user_set",
        related_query_name="core_user",
    )

    def __str__(self):
        return self.username

# ==========================================
# 2. THE PERSONALIZED ROADMAP
# ==========================================

class UserRoadmapItem(models.Model):
    """
    Stores a specific node generated by AI for a specific user.
    """
    STATUS_CHOICES = [
        ('locked', 'Locked'),
        ('active', 'Active (Learning)'),
        ('completed', 'Completed'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='roadmap_items')
    label = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    step_order = models.IntegerField(default=0)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='locked')
    market_value = models.CharField(max_length=20, default="Med")
    project_submission_link = models.URLField(blank=True, null=True)
    submitted_at = models.DateTimeField(auto_now=True)
    resources = models.JSONField(default=dict, blank=True)
    project_prompt = models.TextField(blank=True)
    verification_count = models.IntegerField(default=0)
    custom_cv_text = models.TextField(blank=True, null=True, help_text="User edited achievement text")
    
    def __str__(self):
        return f"{self.user.username} -> {self.label} ({self.status})"

# ==========================================
# 3. COMMUNITY MODELS
# ==========================================

class Skill(models.Model):
    name = models.CharField(max_length=100, unique=True)
    def __str__(self): 
        return self.name

class ProjectReview(models.Model):
    """
    Tracks which users verified which projects (for reputation).
    """
    VOTE_CHOICES = [
        ('up', 'Upvote'),
        ('down', 'Downvote'),
    ]
    submission = models.ForeignKey(UserRoadmapItem, on_delete=models.CASCADE, related_name='reviews')
    reviewer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    vote_type = models.CharField(max_length=10, choices=VOTE_CHOICES, default='up')
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('submission', 'reviewer')

    def __str__(self):
        return f"{self.reviewer.username} verified {self.submission.label}"

class ProjectComment(models.Model):
    project = models.ForeignKey(UserRoadmapItem, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    text = models.TextField(max_length=2000)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"Comment by {self.author.username} on {self.project.label}"

# ==========================================
# 4. STREAK SYSTEM
# ==========================================

class UserActivity(models.Model):
    """
    Tracks daily contribution counts for the streak graph.
    """
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='activities')
    date = models.DateField()
    count = models.IntegerField(default=0)

    class Meta:
        unique_together = ('user', 'date')

# ==========================================
# 5. QUIZ SYSTEM
# ==========================================

class Quiz(models.Model):
    """
    AI-generated quiz for each roadmap module.
    """
    roadmap_item = models.OneToOneField(UserRoadmapItem, on_delete=models.CASCADE, related_name='quiz')
    questions = models.JSONField(help_text="List of question objects with answers")
    user_answers = models.JSONField(default=list, blank=True, help_text="User's submitted answers")
    score = models.IntegerField(default=0, help_text="Score out of 100")
    passed = models.BooleanField(default=False, help_text="True if score >= 70%")
    attempts = models.IntegerField(default=0, help_text="Number of times user took the quiz")
    completed_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"Quiz for {self.roadmap_item.label} - Score: {self.score}%"

# ==========================================
# 6. EMPLOYER PROFILES & JOB POSTINGS
# ==========================================

class EmployerProfile(models.Model):
    """
    Profile for employers/recruiters using the platform.
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='employer_profile')
    company_name = models.CharField(max_length=255)
    company_logo_url = models.URLField(blank=True)
    company_website = models.URLField(blank=True)
    industry = models.CharField(max_length=100, blank=True)
    is_verified = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"{self.company_name}"

class JobPosting(models.Model):
    """
    Job postings created by employers.
    """
    LEVEL_CHOICES = [
        ('intern', 'Internship'),
        ('entry', 'Entry-Level'),
        ('junior', 'Junior'),
    ]
    
    employer = models.ForeignKey(EmployerProfile, on_delete=models.CASCADE, related_name='job_postings')
    title = models.CharField(max_length=255)
    description = models.TextField()
    required_skills = models.JSONField(default=list, help_text="List of required skill keywords")
    level = models.CharField(max_length=10, choices=LEVEL_CHOICES, default='entry')
    location = models.CharField(max_length=255, default='Remote')
    salary_range = models.CharField(max_length=100, blank=True)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"{self.title} at {self.employer.company_name}"

class CandidateApplication(models.Model):
    """
    Tracks applications of learners to job postings.
    """
    STATUS_CHOICES = [
        ('applied', 'Applied'),
        ('reviewed', 'Reviewed'),
        ('shortlisted', 'Shortlisted'),
        ('interview', 'Interview'),
        ('offer', 'Offer'),
        ('rejected', 'Rejected'),
    ]
    
    job_posting = models.ForeignKey(JobPosting, on_delete=models.CASCADE, related_name='applications')
    candidate = models.ForeignKey(User, on_delete=models.CASCADE, related_name='job_applications')
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='applied')
    match_score = models.IntegerField(default=0, help_text="Skill match percentage 0-100")
    applied_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        unique_together = ('job_posting', 'candidate')
    
    def __str__(self):
        return f"{self.candidate.username} -> {self.job_posting.title}"

# ==========================================
# 7. COMMUNITY Q&A MODELS
# ==========================================

class CommunityPost(models.Model):
    POST_TYPES = [
        ('question', 'Question'),
        ('discussion', 'Discussion'),
        ('showcase', 'Project Showcase')
    ]
    
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
    post_type = models.CharField(max_length=20, choices=POST_TYPES, default='question')
    title = models.CharField(max_length=255)
    content = models.TextField()
    
    # Module attachment (optional)
    attached_module = models.ForeignKey(
        UserRoadmapItem, 
        on_delete=models.SET_NULL, 
        null=True, 
        blank=True,
        related_name='community_posts'
    )
    
    # Image upload (optional)
    image = models.ImageField(upload_to='community_images/', null=True, blank=True)
    
    # Engagement metrics
    upvotes = models.IntegerField(default=0)
    view_count = models.IntegerField(default=0)
    reply_count = models.IntegerField(default=0)
    
    # Status
    is_solved = models.BooleanField(default=False)  # For questions
    is_pinned = models.BooleanField(default=False)  # Admin feature
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['-created_at']),
            models.Index(fields=['post_type', '-created_at']),
            models.Index(fields=['attached_module', '-created_at'])
        ]

    def __str__(self):
        return f"{self.title} by {self.author.username}"

class CommunityReply(models.Model):
    post = models.ForeignKey(CommunityPost, on_delete=models.CASCADE, related_name='replies')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='replies')
    content = models.TextField()
    
    # Optional image
    image = models.ImageField(upload_to='reply_images/', null=True, blank=True)
    
    # Engagement
    upvotes = models.IntegerField(default=0)
    is_accepted = models.BooleanField(default=False)  # Best answer (by OP)
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ['-is_accepted', '-upvotes', 'created_at']

    def __str__(self):
        return f"Reply by {self.author.username} on {self.post.title}"

class PostVote(models.Model):
    VOTE_TYPES = [
        ('post', 'Post Vote'),
        ('reply', 'Reply Vote')
    ]
    
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    vote_type = models.CharField(max_length=10, choices=VOTE_TYPES)
    post = models.ForeignKey(CommunityPost, on_delete=models.CASCADE, null=True, blank=True)
    reply = models.ForeignKey(CommunityReply, on_delete=models.CASCADE, null=True, blank=True)
    
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        unique_together = [
            ('user', 'post'),
            ('user', 'reply')
        ]

class PostTag(models.Model):
    name = models.CharField(max_length=50, unique=True)
    posts = models.ManyToManyField(CommunityPost, related_name='tags')
    
    def __str__(self):
        return self.name